{% set version = "3.3.3" %}
{% set sha256 = "edf6453927eee311d4b51afacb52cd5504b2b57cc6d3d92dab9c6bfaf6d883df" %}

package:
  name: yt
  version: {{ version }}

source:
  fn: yt-{{ version }}.tar.gz
  url: http://yt-project.org/sdist/yt-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  script: env EMBREE_DIR=$PREFIX CFLAGS="$CFLAGS -Wno-cpp -fno-strict-aliasing" python setup.py install --single-version-externally-managed --record=record.txt -q | sed -e 's/placehold_//g'  # [not win]
  script: python setup.py install --single-version-externally-managed --record=record.txt -q  # [win]
  entry_points:
    - yt = yt.utilities.command_line:run_main

requirements:
  build:
    - python
    - numpy x.x
    - cython >=0.24.0
    - setuptools >=19.6
    - pyembree  # [linux]
    - gcc  # [linux]
  run:
    - setuptools
    - python
    - numpy x.x
    - h5py
    - sympy
    - matplotlib
    - ipython
    - pyembree  # [linux]
    # for openmp
    - libgcc  # [linux]

test:
  requires:
    - nose
  commands:
    - yt -h
  imports:
    - yt

about:
  home: http://yt-project.org/
  license: BSD 3-clause
  summary: Analysis and visualization toolkit for volumetric data

extra:
    recipe-maintainers:
      - ngoldbaum
      - xarthisius
